version: '3'
services:
  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    depends_on:
      - localstack
    environment:
      - MONGODB_URI=${MONGODB_URI}

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - localstack

  frontend:
    build: ./frontend
    ports:
      - "80:80" # El puerto donde Nginx estará sirviendo la app
    depends_on:
      - product-service
      - order-service

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
