version = "1.0"

# Sección de servicios
[[services]]
name = "frontend"
build = { dockerfile = "frontend/Dockerfile" }

[[services]]
name = "product-service"
build = { dockerfile = "product-service/Dockerfile" }

[[services]]
name = "order-service"
build = { dockerfile = "order-service/Dockerfile" }

[[services]]
name = "localstack"
build = { image = "localstack/localstack" } # No se usa Dockerfile, se especifica la imagen directamente

# Sección de proveedores
[providers]
# Indica que usarás Docker
type = "docker"

# Configuración del entorno de Docker
[docker]
# No es necesario especificar un Dockerfile para la raíz del proyecto si cada servicio tiene su propio
# dockerfile. Este campo puede omitirse si no se necesita un Dockerfile en la raíz.

# Configuraciones adicionales para la imagen de Docker, si es necesario
[build]
context = "." # Asegúrate de que el contexto apunte a la raíz del proyecto
